underlier:
  cost:
    type: RelativeCostFunction
    cost: 3.0e-4
  type: BrownianStock
  mu: 0.0
  sigma: 0.2
derivative:
  type: EuropeanOption
  call: True
  strike: 1.1
  maturity: 0.4
hedge:
  underlier: True
model:
  NTB: False
  type: AQT_NN
  circuit:
    type: SimpleQuantumCircuit
    n_qubits: 5
    n_layers: 5
    # rotation_matrix:
    #   - [y, y, y, y, y]
    #   - [y, y, y, y, y]
    #   - [y, y, y, y, y]
    #   - [y, y, y, y, y]
    #   - [y, y, y, y, y]
    # n_uploads: 3
  in_features: 3
loss:
  type: ExpectedShortfall
  p: 0.1
features:
  - log_moneyness
  - time_to_maturity
  - volatility
training:
  # backup: True
  n_paths: 5000
  n_epochs: 200
  n_times: 1
profit:
  n_paths: 5000
criterion:
  type: ExpectedShortfall
  p: 0.1
benchmark:
  NoHedge: True
  WhalleyWilmott: True
  BlackScholes: True

