underlier:
  type: BrownianStock
  cost:
        type: RelativeCostFunction
#        tolerance: 5.0e-4
#        abscost: 1.0e-2
        cost: 3.0e-4
derivative:
  type: EuropeanOption
  call: True
  strike: 1.1
  maturity: 0.03
hedge:
  underlier: True
model:
  NTB: False
  type: QiskitPreprocessing
  n_qubits: 3
  n_layers: 2
  in_features: 3
loss:
  type: ExpectedShortfall
  p: 0.1
features:
  - log_moneyness
  - time_to_maturity
  - volatility
training:
  n_epochs: 5
  n_paths: 5
  n_times: 1
profit:
  n_paths: 5
criterion:
  type: ExpectedShortfall
  p: 0.1
benchmark:
  NoHedge: True
  WhalleyWilmott: True
  BlackScholes: True